### ISSUE TITLE
ValueError: failed to create intent

### ISSUE THREAD

**Issue by erkhemee** [avisingh599/face-rating#6]
Hi,

Thank you for your share that interesting project.
I am trying to train few model but I'm getting following error,

`python trainModel.py -model linear_model -featuredim 20`

```
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:65: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "trainModel.py", line 25, in <module>
    pca.fit(features_train)
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/pca.py", line 200, in fit
    self._fit(X)
  File "/usr/lib/python2.7/dist-packages/sklearn/decomposition/pca.py", line 249, in _fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/decomp_svd.py", line 100, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

**Comment by getengqing** [comment]
I have the same problem, do you have solving this?
